### ISSUE TITLE
Missing instructions on Yoldark_ETH_staking_dashboard fork

### ISSUE THREAD

**Issue by nicogranuja** [rhmaxdotorg/pulsechain-validator#11]
Hey RHMax, first of all thanks for the scripts and the README it was really helpful .

On the steps where we setup and import the Grafana dashboards we are missing a couple of things on the `Staking Dashboard` section.

When we are importing the file there are a couple more variables to set:
- `node_job: lighthouse`
- `validator_job: lighthouse_validator`

Those are the default values, are these the right values to set?

I am wondering because it is not showing the stats of my validator.

**Comment by rhmaxdotorg** [comment]
You're welcome!

Hmmm I think whatever pops up as the default should be the right ones for node_job and validator_job. Are you using the original ETH Yoldark dashboard or the PLS forked one @ https://github.com/raskitoma/pulse-staking-dashboard?

**Comment by nicogranuja** [comment]
Yes I am using the forked one, I left the default values, but It does not work and I thought I was missing the initial correct default values. Attached is the image of what I see
<img width="1911" alt="Screen Shot 2023-05-05 at 9 53 06 PM" src="https://user-images.githubusercontent.com/17203717/236594957-4a507889-4e89-4970-b8f0-63b1786c595a.png">

I am wondering does it need to bake for several days before it shows any data? Or does it work for you?

**Comment by rhmaxdotorg** [comment]
The top of the dashboard may not have values for the first couple days as I noticed as well.

How about the rest of the stats and charts? Those are showing on mine.

**Comment by nicogranuja** [comment]
No luck on that fron either, completely blank in some stats, I have several validators and none are showing.
<img width="1912" alt="Screen Shot 2023-05-06 at 9 35 32 AM" src="https://user-images.githubusercontent.com/17203717/236630680-fe91f8c5-dc5c-4ffe-b698-80988fbfad1d.png">

**Comment by nicogranuja** [comment]
No luck on that fron either :( I have several validators and none are showing
<img width="1912" alt="Screen Shot 2023-05-06 at 9 35 32 AM" src="https://user-images.githubusercontent.com/17203717/236630739-a571c745-91f3-4508-8612-029f9829d019.png">


Update: Also I found out the main repo was having issues after the Shanghai upgrade went through on Ethereum https://github.com/Yoldark34/lighthouse-staking-dashboard/issues/6

**Comment by rhmaxdotorg** [comment]
That's strange. Do you used the monitoring setup script, following the guidance on the README to import the dashboards, used the default values from the drop-down boxes at import stage, but don't see the stats?

Has it been more than 1-2 days? As that's the process I've (and others I've worked with) have followed and it seems to be working here. Hmm..

**Comment by nicogranuja** [comment]
Just an update on this, even after 2 days it would still not show any data, I have a theory and maybe it doesn't support up to N validators but only < N. 

I re-did the whole process on a new EC2 instance, (first time did it on a NUC) this time will try just adding 10 validators and wait another 24-48 hours, it is very strange that I am the only one it does not work for given that instructions are pretty straigth forward and hard to mess up.
Will keep this thread open and add any findings, but feel free to close or suggest another dashboard if there's another one folks are using to see their validators.

Thanks

**Comment by rhmaxdotorg** [comment]
hmm yeah that one is "the best" dashboard I know of. hope you figure it out!

yes interested in any findings.

**Comment by nicogranuja** [comment]
Confirmed to be working after 1.4 days, very strange the other one did not work after 2 days
Thanks

**Comment by rhmaxdotorg** [comment]
excellent! glad it finally starting working.

**Comment by nicogranuja** [comment]
Anyone trying to get metrics and having more than 64 validators, see: https://github.com/raskitoma/pulse-staking-dashboard/issues/6
