### ISSUE TITLE
Geth wont run code=Exited

### ISSUE THREAD

**Issue by StianNOR** [rhmaxdotorg/pulsechain-validator#14]
![image](https://user-images.githubusercontent.com/82333847/236939767-1dfec667-560d-46e4-b7f3-4813a13789d9.png)
For some reason i have problems whit Geth running any idea? i wasted a day now hahaha

**Comment by StianNOR** [comment]
Was error in the geth folder so i git cloned from gitlab and make all. after that everything worked. Why this was a problem i dont know. but up and running and syncing now.

**Comment by rhmaxdotorg** [comment]
great!

try restarting geth with systemctl if you have issues in the future as sometimes that works too. lots of debugging commands in the README.
