### ISSUE TITLE
Getting ready for the Mainnet

### ISSUE THREAD

**Issue by dkim777** [rhmaxdotorg/pulsechain-validator#16]
Ok, RH said the Mainnet will be live in 7days.
What should we expect from validator point of the view?

by the way, do we need to download the whole new blockchain data(gETH)?  sorry I'm not that familiar with the difference between testnet and mainnet blockchain 

Thanks!

**Comment by rhmaxdotorg** [comment]
I talked about this during the last couple AMAs, feel free to check them out by searching on YT: "rhmax validator ama mainnet"

But yes, I plan on starting from a clean validator box, running the (updated) script which I will post as soon as I can after launch with 2-3 days total turnaround time to get on the network (if all goes well) -- that's 1-2 days to complete syncing the blockchain and hopefully within (1) day to get activated on the network as a validator after making the deposit.
