### ISSUE TITLE
Adding a validator

### ISSUE THREAD

**Issue by rumblersull** [rhmaxdotorg/pulsechain-validator#17]
Hey, I am trying to add a validator to my existing set on the same server without having to generate new seed words. I believe there is an instruction set around this but am not clear  if I need to shut down my server and then restart it (which I'd prefer not to). Perhaps you can cover this topic in the repo? Thanks a bunch for everything you do for the community.

**Comment by rhmaxdotorg** [comment]
Actually, it's already covered in the FAQ section in the README.

I haven't tested it myself on mainnet, but there's a link to coincashew guidance and seems straightforward as long as you get the parameters right.
