### ISSUE TITLE
LIGHTHOUSE_VALIDATOR_DATA is not used

### ISSUE THREAD

**Issue by augchan42** [rhmaxdotorg/pulsechain-validator#19]
From inspecting and running the pulsechain-validator-setup.sh script, it seems LIGHTHOUSE_VALIDATOR_DATA is not used when setting up the systemd setup file for the Lighthouse Validator.

**Comment by rhmaxdotorg** [comment]
huh, that does appear to be the case. it probably was leftover from some initial testing.

will remove it, thanks!

**Comment by rhmaxdotorg** [comment]
https://github.com/rhmaxdotorg/pulsechain-validator/commit/0dcaa2856f6b6d0f595192ec4102e761490971d4
