### ISSUE TITLE
Difference from Testnet and Mainnet no payout.

### ISSUE THREAD

**Issue by StianNOR** [rhmaxdotorg/pulsechain-validator#20]
Hey i tried to find some info about this but i cant find any.
On test net we got the validator income directly to our fee address, but here on mainnet its looks like that's not working.

Is this because of the high tx fee's now compare to testnet? Or is something changed ?

From what i can see the income from validator coming directly to the Deposited collateral on the node, No income shows on my fee address added or the withdrawal address that was set. 

Any idea or am i the only one ;)

**Comment by StianNOR** [comment]
Dont look like i get any payout. Is there some setting i have missed?

My Validator:
https://beacon.pulsechain.com/validator/0xb652b9155f824c02ca0935ef087a1dbd8a2fcf05fa2fbcbba933be42c28239f5b72e7f26751827085a3f7b3b70e8677d#charts

**Comment by rhmaxdotorg** [comment]
Interesting.. I have seen automatic withdrawals on other validators for sure and pretty regularly.

I'm not sure why you're note seeing deposits occur. You can ask in t.me/PulseDev and see if anyone knows there though.

**Comment by StianNOR** [comment]
Yeah the problem is that nobody have time, and its just flooding over whit scammers. i see i need to make the./deposit.sh generate-bls-to-execution-change. but i get error  

[Error] The given withdrawal credentials does not match the old BLS withdrawal credentials that mnemonic generated.

So i am stuck i have no idea what to do. Now i guess everything is stuck.
