### ISSUE TITLE
Lighthouse sync

### ISSUE THREAD

**Issue by gazaz** [rhmaxdotorg/pulsechain-validator#25]
After the most recent update, my lighthouse client doesn't seem to fully sync and stops with 352 to go. Restarted lighthouse, but doesn't seem to complete. All seems to be working ok on the beacon explorer though. Should I be worried about that ?

$ curl -s http://localhost:5052/lighthouse/syncing | jq
{
  "data": {
    "BackFillSyncing": {
      "completed": 0,
      "remaining": 352
    }
  }
}

**Comment by rhmaxdotorg** [comment]
Hey @gazaz, good question!

I noticed something similar with mine over the last couple weeks too, however the Beacon explorer shows 100% effectiveness and all good as far as rewards.

Are you in the [PulseDev](https://t.me/PulseDev) group?

I'll ask this question and see if anyone is reporting Lighthouse issues.

**Comment by rhmaxdotorg** [comment]
I haven't heard much back on TG, and as validator effectiveness % nor rewards are being impacted, I'm going to close this for now as it could be a client issue or something else.
