### ISSUE TITLE
MEV-boost

### ISSUE THREAD

**Issue by wishbonesr** [rhmaxdotorg/pulsechain-validator#27]
I hate to use this simply as a communication tool, but I'm wondering about MEV-boosting.
Ex. `https://github.com/flashbots/mev-boost`
Is MEV-boosting a thing on pulse?  or does the block scheduler make MEV-boosting moot on Pulse?
Is there a Pulse equivalent.  If no equivalent and valid on Pulse, looks like I found my next project.

**Comment by rhmaxdotorg** [comment]
I think HexPleb might know more about this. I'll send this post over to him and see if he wants to chime in.

**Comment by rhmaxdotorg** [comment]
Spoke with him and sounds like it would need to be forked over.
