### ISSUE TITLE
Ports and Protocols

### ISSUE THREAD

**Issue by dkim777** [rhmaxdotorg/pulsechain-validator#3]
Thanks for the scripts!
Can you add Ports and Protocols section for those users running it behind the Firewall or NAT gateway?

I'm assuming the IP address you enter when running the initial install script is the public IP?
Thanks.

**Comment by rhmaxdotorg** [comment]
thank you!

that's a good idea, will try and add them this weekend. And yes, the install script expects your public IP address.

**Comment by rhmaxdotorg** [comment]
Fixed with https://github.com/rhmaxdotorg/pulsechain-validator/commit/13cb8cec51d350dbd954f98981e19c6bb82f4dc3

**Comment by dkim777** [comment]
Thanks for the quick update.
Is there a way to change ETHEREUM FEE ADDRESS and/or Server IP address
after the installation?
Thanks

**Comment by rhmaxdotorg** [comment]
another good idea!

could you open a separate issue @dkim777 so I can track it?
