### ISSUE TITLE
update OS or update client?

### ISSUE THREAD

**Issue by dkim777** [rhmaxdotorg/pulsechain-validator#32]
Can I update the ubuntu OS update (sudo apt update && apt upgrade) without causing issues to my validators?
or should I just run update-client.sh script?
How do I know when I should run update-client.sh ?

Thanks!

**Comment by rhmaxdotorg** [comment]
hey @dkim777, good questions.

I don't plan on doing OS updates very often (some servers go months or years without updates, exception is critical security ones that actually affect your system, most of which do not), however I don't anticipate issues when doing so with the clients. Some weird dependency mismatch ones are possible I guess, but I wouldn't worry about having to rebuild the validator after doing OS updates.

For update-client.sh, I also only plan on running it when I see PulseChain devs release critical updates that affect Geth and Lighthouse (the two clients relevant for this particular validator script and system), which isn't likely often either.

Let me know if you have any further questions!

**Comment by dkim777** [comment]
What should I do if my attestation suddenly start going up?
![image](https://github.com/rhmaxdotorg/pulsechain-validator/assets/12587920/c7eafc3d-3312-43f9-bb52-cd3c7eb6ab9b)
