### ISSUE TITLE
EXIT validators without the validator system

### ISSUE THREAD

**Issue by dkim777** [rhmaxdotorg/pulsechain-validator#33]
There's an EXIT instruction on the readme file but.
How do you EXIT without the validator functioning?

for example, your system crashed and burned and there's no way to recover your validator node/system/pc
how do you exit and re-claim your cryptos?

Thanks!

**Comment by rhmaxdotorg** [comment]
Interesting... well, maybe this is helpful. As long as you have your keys, you should be able to load them up on new hardware and exit.

However, if you lost your keys, not sure if a graceful exit is possible and I guess it will remain on the network until deprecated is my best guess.
