### ISSUE TITLE
Uninstall Script?

### ISSUE THREAD

**Issue by dkim777** [rhmaxdotorg/pulsechain-validator#35]
Is there anyway to uninstall/remove/delete this installation?

**Comment by rhmaxdotorg** [comment]
There is `reset-validator.sh` and `reset-monitoring.sh` which essentially uninstall everything (except `reset-validator.sh` keeps blockchain data in /opt by default, but this can be changed).

Is that what you're looking for?

**Comment by dkim777** [comment]
I originally thought reset was the one but it only resets config.
I need something to delete all the apps it installed, closes all the ports it opened.
including Monitoring system Grafana and Premetheus please.
Thanks

**Comment by rhmaxdotorg** [comment]
Hmm, that would probably be an update to the `reset-validator.sh` script or it might be better to separate it entirely with `reset-server.sh` script.

List of things to undo:
- apt packages @ https://github.com/rhmaxdotorg/pulsechain-validator/blob/main/pulsechain-validator-setup.sh#L40
- rust @ https://github.com/rhmaxdotorg/pulsechain-validator/blob/main/pulsechain-validator-setup.sh#L123
- firewall rules @ https://github.com/rhmaxdotorg/pulsechain-validator/blob/main/pulsechain-validator-setup.sh#L263
- jwt secret @ https://github.com/rhmaxdotorg/pulsechain-validator/blob/main/pulsechain-validator-setup.sh#L64
- blockchain data @ https://github.com/rhmaxdotorg/pulsechain-validator/blob/main/reset-validator.sh#L31 (again this can be done with the reset script)

There's really not a lot of remove other than the minimal apt packages and Rust...

But I'd be curious why the reset script wouldn't be sufficient as-is as you can always just wipe the server (or in the cloud, destroy the instance and create a new one) as well which is what I would tend to do for a "full" reset.

**Comment by dkim777** [comment]
I did run reset-validator.sh but still left with open ports below.
some are for the Grafana but some are for validators.

`State         Recv-Q        Send-Q                      Local Address:Port                        Peer Address:Port         Process
LISTEN        0             4096                            127.0.0.1:8088                             0.0.0.0:*
LISTEN        0             4096                              0.0.0.0:3306                             0.0.0.0:*
LISTEN        0             4096                        127.0.0.53%lo:53                               0.0.0.0:*
LISTEN        0             128                               0.0.0.0:22                               0.0.0.0:*
ESTAB         0             0                               127.0.0.1:55916                          127.0.0.1:9100
ESTAB         0             0                            192.168.0.52:22                         192.168.0.160:24854
LISTEN        0             4096                                    *:3000                                   *:*
LISTEN        0             4096                                    *:9090                                   *:*
LISTEN        0             4096                                 [::]:3306                                [::]:*
LISTEN        0             4096                                    *:9100                                   *:*
LISTEN        0             4096                                    *:8086                                   *:*
LISTEN        0             128                                  [::]:22                                  [::]:*
ESTAB         0             0                      [::ffff:127.0.0.1]:9100                  [::ffff:127.0.0.1]:55916`

**Comment by rhmaxdotorg** [comment]
3000 is Grafana and 9090 is Prometheus (there is a reset-monitoring.sh script to remove them).

The rest I don't see being validator clients as those are ports 9000 and 30303 (which aren't listed), so looks like other service ports on the server.

**Comment by dkim777** [comment]
Was influxd installed as part of your install script?
port 8086
    *:8086                      *:*         users:(("influxd",pid=669,fd=25))

**Comment by rhmaxdotorg** [comment]
Maybe with grafana, but I'm not sure.

The `reset-monitoring.sh` should remove all the Grafana / Prometheus stuff.

Going to close this one for now as I think it's resolved, but feel free to re-open if not.
