### ISSUE TITLE
update-client.sh - error

### ISSUE THREAD

**Issue by TzBaker** [rhmaxdotorg/pulsechain-validator#36]
Hi there,

I'm trying update cliets using update-client.sh and get errors: 
-----------------------------------------------------------------------------------------=
~/pulsechain-validator$ ./update-client.sh
ARE YOU SURE YOU WANT TO GO OFFLINE TO STOP, UPDATE AND RESTART PULSECHAIN CLIENTS ON THE VALIDATOR?

* it could take 30 - 60 minutes to complete -- depending mostly on bandwidth and server specs *

Hit [Enter] to Continue OR Ctrl+C to Cancel

Step 1: Stop PulseChain clients (Geth and Lighthouse)
[sudo] password for deltaplan:
**sudo: node: command not found**

Step 2: Pull updates and rebuild clients

**fatal: not a git repository (or any of the parent directories): .git**
info: using existing install for 'stable-x86_64-unknown-linux-gnu'
info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.70.0 (90c541806 2023-05-31)

**fatal: not a git repository (or any of the parent directories): .git**

Step 3: Starting PulseChain clients

Process is complete
--------------------------------------------------------------------------------------------=
Can you please help me to fix it?

Thanks!

**Comment by rhmaxdotorg** [comment]
Hey there,

First question: did you use this the validator setup script https://github.com/rhmaxdotorg/pulsechain-validator/blob/main/pulsechain-validator-setup.sh to setup your validator or did you set it up using something else?

The update script ONLY works if you used this repo's script script to install the validator.

I can't think of any other reason why it wouldn't update the clients unless "sudo" app isn't installed or you're running it in a different shell or environment that doesn't like the script.

**Comment by TzBaker** [comment]
I used all your instructions to setup validator and yes I used  https://github.com/rhmaxdotorg/pulsechain-validator/blob/main/pulsechain-validator-setup.sh on June 26, 2023.

**Comment by rhmaxdotorg** [comment]
Ah, I think I see what the problem might be.

See the guidance link below for the update script. Unfortunately, there was an issue with it that affects validators setup with this script prior to early July 2023.

https://github.com/rhmaxdotorg/pulsechain-validator#client-update-script

There are a couple options here as we worked on making the "quick rebuild" process as easy as possible.

**Comment by TzBaker** [comment]
Thank you! I'll try it.

**Comment by TzBaker** [comment]
Thank you! I'll try it.
