### ISSUE TITLE
Error in lighthouse

### ISSUE THREAD

**Issue by dkim777** [rhmaxdotorg/pulsechain-validator#39]
I'm getting these errors in both beacon and validator services.
Normally I just reboot but thought I check this time.
any ideas?

journalctl -u lighthouse-beacon.service -f
Sep 10 16:51:55 validator3 lh[905]: Sep 10 20:51:55.002 WARN Error processing HTTP API request       method: POST, path: /eth/v1/validator/duties/sync/131840, status: 400 Bad Request, elapsed: 218.586µs

journalctl -u lighthouse-validator.service -f
Sep 10 16:52:55 validator3 lh[909]: Sep 10 20:52:55.002 ERRO Failed to download attester duties      err: FailedToDownloadAttesters("Some endpoints failed, num_failed: 2 http://localhost:5052/ => Unavailable(NotSynced), http://localhost:5052/ => RequestFailed(ServerMessage(ErrorMessage { code: 400, message: \"BAD_REQUEST: Unsupported endpoint version: v1\", stacktraces: [] }))"), request_epoch: 131925, current_epoch: 131925, service: duties

**Comment by dkim777** [comment]
Just so you know, there's no network issue.
and restarted Geth, lighthouse-beacon, lighthouse-validator services but still getting same error messages.

**Comment by rhmaxdotorg** [comment]
Hmm I have not seen these errors before.

Things I can think of that I would try to do:
- Reboot
- If not running the latest versions of the clients, updating them and seeing if a rebuild of the clients makes a difference
- Last resort: reset script (or worst case, configure reset script to also remove blockchain data to do a "clean" sync)

**Comment by dkim777** [comment]
Reboot, fixed it somehow.
I will try to update the OS and the client after about a week of stable run.
Thanks!
