### ISSUE TITLE
Clarification variable LIGHTHOUSE_WALLET_DATA

### ISSUE THREAD

**Issue by i-d-two** [rhmaxdotorg/pulsechain-validator#4]
Just to double check if I'm missing something..

The  variable [LIGHTHOUSE_WALLET_DATA](https://github.com/rhmaxdotorg/pulsechain-validator/blob/d7ed75fce68d179ad1be2dcb327c8d825422726f/pulsechain-validator-setup.sh#L68) gets declared, later on a directory gets created with the variable but then the directory stays empty and unused as far as I can tell...

Checked on a running system after a successful install process with the script, the dir is basically empty.

Am I doing something wrong, or what were you planing to do with that dir?

**Comment by rhmaxdotorg** [comment]
good catch!

it was probably left over from the original script where I was testing erigon and prysm on ethereum testnet, will remove it from the script.

**Comment by rhmaxdotorg** [comment]
Fixed in https://github.com/rhmaxdotorg/pulsechain-validator/commit/4e39a41cc6cc9c7323f2556bdeb6001d2f9d9f91
