### ISSUE TITLE
Is there a way to change ETHEREUM FEE ADDRESS and/or Server IP address after the installation?

### ISSUE THREAD

**Issue by dkim777** [rhmaxdotorg/pulsechain-validator#5]
I sometimes move my server to different network and the IP address change.
It would be nice if we can change the IP address of the existing installation without the reset and whole new install.

and same for ETHEREUM FEE ADDRESS

Thanks for your help!

by the way, I used internal IP address instead of the public IP and it will seem to be working and communicating ok with other peers?

**Comment by rhmaxdotorg** [comment]
good idea!

committed @ https://github.com/rhmaxdotorg/pulsechain-validator/commit/458c5ba52592c506eb71cab91968c7ad134121db
