### ISSUE TITLE
Blockchain copy instead of download

### ISSUE THREAD

**Issue by dkim777** [rhmaxdotorg/pulsechain-validator#6]
I need to setup another Validator.
Is there a way to just copy the eth blockchain data from my existing Validator instead of waiting for another 5days to download?
Thanks for your help!

**Comment by rhmaxdotorg** [comment]
hmm, if you have already downloaded it somewhere else and made a copy of it, sure.

for example, if you're using AWS cloud and do a snapshot of the server where the blockchain data is downloaded, you can use it. OR if you have it downloaded on a hard disk somewhere on your network, you can copy it over from there. but it *should* only take a day or two to sync the PulseChain testnet right now (depends on your bandwidth).

**Comment by rhmaxdotorg** [comment]
might have an idea for a snapshot script, let me think more of this one

**Comment by dkim777** [comment]
Where are the blockchain files located?
I tried to look at   /home/node/.ethereum   but that folder doesn't exist.

**Comment by dkim777** [comment]
Maybe I can just copy the /opt/geth/data/geth/chaindata folder to new Validator installation ?

**Comment by rhmaxdotorg** [comment]
yeah the blockchain data is in /opt/geth/data and /opt/lighthouse/beacon, working on a script to zip them up so they can be copied to another machine

**Comment by dkim777** [comment]
It's over 500GB,  how about a simple script to just copy from one machine
to another via either SCP or NFS mount?

Also, if you use the RESET-VALIDATOR.SH script, looks like it deletes the
blockchain data, any option to keep it for re-installation of the Validator?

**Comment by rhmaxdotorg** [comment]
writing a script to do the actual copy gets a little complicated, because does the server receiving the copy use password auth or key auth, etc... I'll probably write the script to package up the blockchain files and include an example scp (secure copy) command to transfer it over the network.

Or if its your own hardware, a usb stick works.

for the reset validator script, that's a good idea. I'll see if I can make it by default NOT delete the blockchain data.

**Comment by rhmaxdotorg** [comment]
updated the reset script @ https://github.com/rhmaxdotorg/pulsechain-validator/commit/d0eba6212ae85c7178dbdb55b037b7ed5fa0024a

still testing the snapshot script, it takes a long time to compress the blockchain data so it also takes a long time to test the script

**Comment by rhmaxdotorg** [comment]
still testing this one

**Comment by rhmaxdotorg** [comment]
ok, here's a snapshot script @ https://github.com/rhmaxdotorg/pulsechain-validator/commit/9c0ae0a50561b89dc185d7cda83db03f945f087b
