### ISSUE TITLE
Running multiple Validators

### ISSUE THREAD

**Issue by dkim777** [rhmaxdotorg/pulsechain-validator#7]
Can I run multiple Validators on a same host?
It would be nice to add an option to install multiple validators in the script but I wouldn't mind repeating the same process as long as they don't cause conflict or collide.
Thanks!

**Comment by rhmaxdotorg** [comment]
Yes, you can run as many validators as you want on one host.

The setup script has no dependencies on the number of validators you run, it simply installs the clients and when you generate your validator keys with the staking deposit tool, there you choose the specific number you want to run. It could be 1, 5, 10 or 100. Then, when you import your keys to Lighthouse, you will import each key and it will configure the client to run that number of validators.

Good question though! Adding this to the wiki now.

**Comment by rhmaxdotorg** [comment]
Fixed

https://github.com/rhmaxdotorg/pulsechain-validator/commit/0edc30b343487b13a09af7c0347725cc4bd918df

**Comment by dkim777** [comment]
Sorry I have missed that FAQ,
Does it mean that I can also increase the number of existing Validators by
running that same lighthouse import script to ADD more validators?
after creating additional validator keys of course.
Thanks.

**Comment by rhmaxdotorg** [comment]
hmm, I'm not sure if you can adjust the number of validators (but I might have heard Gamma mentioned this), but if you can it would probably be with the deposit client / recovery and then importing the additional ones back in.
