### ISSUE TITLE
missing dependecies after recent update..

### ISSUE THREAD

**Issue by oszkari** [rhmaxdotorg/pulsechain-validator#8]
Hi, 

pulsechain validator script has some  issues after the recent update..with a fresh install directories seem to be missing..
Can you please take a look when you have a moment. Thanks!

step 3: setting up and running Geth (execution client) to start syncing data

Cloning into 'go-pulse'...
remote: Enumerating objects: 109741, done.
remote: Counting objects: 100% (10772/10772), done.
remote: Compressing objects: 100% (3162/3162), done.
remote: Total 109741 (delta 7456), reused 10772 (delta 7456), pack-reused 98969
Receiving objects: 100% (109741/109741), 158.11 MiB | 29.68 MiB/s, done.
Resolving deltas: 100% (76316/76316), done.
mv: target '/opt/geth' is not a directory
chown: cannot access '/opt/geth': No such file or directory
./pulsechain-validator-setup.sh: line 129: cd: /opt/geth: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
Created symlink /etc/systemd/system/default.target.wants/geth.service → /etc/systemd/system/geth.service.

step 4: setting up Lighthouse (beacon and validator client)

/home/oszkari/pulsechain-validator
Cloning into 'lighthouse-pulse'...
remote: Enumerating objects: 66065, done.
remote: Counting objects: 100% (5659/5659), done.
remote: Compressing objects: 100% (2370/2370), done.
remote: Total 66065 (delta 3800), reused 4677 (delta 3208), pack-reused 60406
Receiving objects: 100% (66065/66065), 96.10 MiB | 26.05 MiB/s, done.
Resolving deltas: 100% (43708/43708), done.
mv: target '/opt/lighthouse' is not a directory
chown: cannot access '/opt/lighthouse': No such file or directory
./pulsechain-validator-setup.sh: line 183: cd: /opt/lighthouse: No such file or directory
make: stat: GNUmakefile: Permission denied
make: stat: makefile: Permission denied
make: stat: Makefile: Permission denied
make: *** No targets specified and no makefile found.  Stop.
ln: failed to create symbolic link '/opt/lighthouse/lighthouse/lh': No such file or directory
Created symlink /etc/systemd/system/multi-user.target.wants/lighthouse-beacon.service → /etc/systemd/system/lighthouse-beacon.service.
Created symlink /etc/systemd/system/multi-user.target.wants/lighthouse-validator.service → /etc/systemd/system/lighthouse-validator.service.

**Comment by rhmaxdotorg** [comment]
thanks for reporting it and sorry about that!

I updated the reset script recently, which triggered a whole bunch of things and retesting, and I needed to then change to make the setup script work in different scenarios.

try this fix @ https://github.com/rhmaxdotorg/pulsechain-validator/commit/375ab0086b89d8e294a93cd44699475023cba9aa

**Comment by oszkari** [comment]
thanks for doing this for the community!

**Comment by rhmaxdotorg** [comment]
my pleasure. we win together!
